name: peloton_communicator
description: A new Flutter project.

version: 0.0.3

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  flutter_sound: ^9.2.13
  permission_handler: ^9.0.0
  package_info_plus: ^3.0.3
  mqtt_client: ^9.8.1
  path_provider: ^2.0.14
  logger: ^1.3.0
  typed_data: ^1.3.1
  flutter_dotenv: ^5.0.2
  device_info_plus: ^8.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/certificates/
    - assets/certificates/thing-certificate.pem.crt
    - assets/certificates/thing-private.pem.key
    - assets/certificates/thing-public.pem.key
